# Generated by Django 3.2 on 2022-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220409_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhaar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='f_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='l_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone_no',
            field=models.IntegerField(blank=True),
        ),
    ]
