# Generated by Django 3.2 on 2022-04-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220409_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_no',
            field=models.CharField(default='ABC', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='min_fee',
            field=models.IntegerField(default=200),
        ),
    ]
